services:
  db:
    image: mariadb
    networks:
      - db-admin
    environment:
      - MYSQL_ROOT_PASSWORD=123

  admin:
    image: phpmyadmin
    networks:
      - db-admin
    ports:
      - "8081:80"
networks:
  db-admin: 
